# Generated by Django 5.2.8 on 2026-01-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='home/')),
                ('link', models.CharField(choices=[('/devops/', 'DevOps'), ('/blogs/', 'Blogs')], max_length=50)),
            ],
        ),
    ]
